"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Edit2, MapPin, Plus, RefreshCw, Search, Warehouse as WarehouseIcon } from "lucide-react";
import AppShell from "../../components/app-shell";
import { EmptyStateView, ErrorStateView, LoadingSpinner } from "../../components/ui/state-views";
import { Modal } from "../../components/ui/modal";
import { StatusBadge } from "../../components/ui/badge";
import { listBranches } from "../../lib/branches";
import { createWarehouse, listWarehouseInventory, listWarehouses, updateWarehouse } from "../../lib/warehouses";
import { formatCurrency, formatNumber } from "../../components/dashboard/stat-card";
import type { Warehouse } from "../../types/warehouses";

export default function WarehousesPage() {
  const queryClient = useQueryClient();
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<Warehouse | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [name, setName] = useState("");
  const [code, setCode] = useState("");
  const [branchId, setBranchId] = useState("");
  const [error, setError] = useState("");
  const warehousesQuery = useQuery({ queryKey: ["warehouses", search], queryFn: () => listWarehouses({ q: search || undefined }) });
  const branchesQuery = useQuery({ queryKey: ["branches"], queryFn: () => listBranches() });
  const inventoryQuery = useQuery({ queryKey: ["warehouse-inventory", selected?.id], queryFn: () => listWarehouseInventory({ warehouse_id: selected?.id }), enabled: !!selected });
  const mutation = useMutation({ mutationFn: () => createWarehouse({ name: name.trim(), code: code.trim(), branch_id: branchId }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["warehouses"] }); setFormOpen(false); setError(""); setName(""); setCode(""); }, onError: (err: Error) => setError(err.message) });
  const deactivateMutation = useMutation({ mutationFn: (id: string) => updateWarehouse(id, { is_active: false }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["warehouses"] }); setSelected(null); }, onError: (err: Error) => setError(err.message) });
  const branches = branchesQuery.data ?? [];
  const branchMap = new Map(branches.map((branch) => [branch.id, branch.name]));
  const warehouses = warehousesQuery.data ?? [];
  const inventory = inventoryQuery.data ?? [];

  return <AppShell><div className="mx-auto w-full max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:px-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Inventory Network</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Warehouses</h1><p className="mt-1 text-xs text-slate-500">Manage stock locations, available quantities, reorder signals, and inventory value.</p></div><div className="flex gap-2"><button type="button" onClick={() => warehousesQuery.refetch()} className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-white px-3 py-2 text-xs font-semibold text-slate-700"><RefreshCw className="h-3.5 w-3.5" /> Refresh</button><button type="button" onClick={() => { setError(""); setFormOpen(true); }} className="inline-flex items-center gap-1.5 rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-white"><Plus className="h-4 w-4" /> Add Warehouse</button></div></header>
    <div className="relative max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search warehouses by name or code..." className="w-full rounded-lg border border-border bg-white py-2 pl-9 pr-3 text-xs outline-none focus:border-primary" /></div>
    {warehousesQuery.isLoading ? <LoadingSpinner message="Loading warehouses..." /> : warehousesQuery.isError ? <ErrorStateView message="Unable to load warehouses." onRetry={() => warehousesQuery.refetch()} /> : warehouses.length === 0 ? <EmptyStateView title="No warehouses" message="Add a warehouse to begin tracking location-specific stock." /> : <div className="grid gap-4 lg:grid-cols-3">{warehouses.map((warehouse) => <button type="button" key={warehouse.id} onClick={() => setSelected(warehouse)} className="rounded-xl border border-border bg-white p-5 text-left shadow-sm transition hover:border-primary/40 hover:shadow-md"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><WarehouseIcon className="h-5 w-5" /></div><StatusBadge status={warehouse.is_active ? "Active" : "Inactive"} /></div><h2 className="mt-4 text-base font-semibold text-slate-950">{warehouse.name}</h2><p className="mt-1 text-xs font-medium text-slate-500">{warehouse.code}</p><p className="mt-3 flex items-center gap-1.5 text-xs text-slate-500"><MapPin className="h-3.5 w-3.5" />{branchMap.get(warehouse.branch_id) ?? "Branch"}</p></button>)}</div>}
    <Modal isOpen={!!selected} onClose={() => setSelected(null)} title={selected?.name ?? "Warehouse details"} description={selected ? `${selected.code} · ${branchMap.get(selected.branch_id) ?? "Branch"}` : undefined} maxWidth="xl">{selected && <div className="space-y-4 text-xs"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Items tracked" value={formatNumber(inventory.length)} /><Metric label="Inventory value" value={formatCurrency(inventory.reduce((sum, item) => sum + Number(item.inventory_value), 0))} /><Metric label="Low stock" value={formatNumber(inventory.filter((item) => Number(item.available_quantity) <= Number(item.reorder_level)).length)} /></div>{inventory.length === 0 ? <EmptyStateView title="No warehouse stock" message="Receive or adjust stock to populate this location." /> : <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full text-left"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-3 py-2">Product</th><th className="px-3 py-2">Quantity</th><th className="px-3 py-2">Reserved</th><th className="px-3 py-2">Available</th><th className="px-3 py-2">Value</th></tr></thead><tbody className="divide-y divide-border">{inventory.map((item) => <tr key={item.id}><td className="px-3 py-2 font-medium">{item.product_id.slice(0, 8)}...</td><td className="px-3 py-2">{item.quantity}</td><td className="px-3 py-2">{item.reserved_quantity}</td><td className="px-3 py-2">{item.available_quantity}</td><td className="px-3 py-2">{formatCurrency(item.inventory_value)}</td></tr>)}</tbody></table></div>}<button type="button" onClick={() => deactivateMutation.mutate(selected.id)} disabled={!selected.is_active || deactivateMutation.isPending} className="rounded-lg border border-rose-200 px-3 py-2 font-semibold text-rose-600 disabled:opacity-40">Deactivate warehouse</button></div>}</Modal>
    <Modal isOpen={formOpen} onClose={() => setFormOpen(false)} title="Add Warehouse" description="Connect a stock location to an existing branch."><form onSubmit={(event) => { event.preventDefault(); if (!name.trim() || !code.trim() || !branchId) { setError("Name, code, and branch are required."); return; } mutation.mutate(); }} className="space-y-4 text-xs">{error && <div className="rounded-lg bg-rose-50 p-3 text-rose-700">{error}</div>}<label className="block space-y-1 font-semibold">Name<input required value={name} onChange={(event) => setName(event.target.value)} className="w-full rounded-lg border border-border px-3 py-2 font-normal" /></label><label className="block space-y-1 font-semibold">Code<input required value={code} onChange={(event) => setCode(event.target.value)} className="w-full rounded-lg border border-border px-3 py-2 font-normal" /></label><label className="block space-y-1 font-semibold">Branch<select required value={branchId} onChange={(event) => setBranchId(event.target.value)} className="w-full rounded-lg border border-border px-3 py-2 font-normal"><option value="">Select branch</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setFormOpen(false)} className="rounded-lg border border-border px-4 py-2 font-semibold">Cancel</button><button type="submit" disabled={mutation.isPending} className="rounded-lg bg-primary px-4 py-2 font-semibold text-white">{mutation.isPending ? "Saving..." : "Save Warehouse"}</button></div></form></Modal>
  </div></AppShell>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-3"><p className="text-slate-500">{label}</p><p className="mt-1 text-base font-bold text-slate-950">{value}</p></div>; }
